services:
  Batoi\Aif\Symfony\SymfonyExecutionContextResolver: ~

  Batoi\Aif\Gateway\AifGateway:
    factory: ['Batoi\Aif\Symfony\AifFactory', 'gateway']
    arguments:
      $config: '%batoi_aif%'

  Batoi\Aif\Api\AifApi:
    arguments:
      $gateway: '@Batoi\Aif\Gateway\AifGateway'
      $contextResolver: '@Batoi\Aif\Symfony\SymfonyExecutionContextResolver'

  Batoi\Aif\Symfony\AifController:
    arguments:
      $aif: '@Batoi\Aif\Api\AifApi'
    tags: ['controller.service_arguments']
